name = "space-terminal"
compatibility_date = "2024-02-06"
pages_build_output_dir = "./dist"

[env.production]
vars = { }  # Environment variables will be set in Cloudflare dashboard

[env.preview]
vars = { }  # Environment variables will be set in Cloudflare dashboard

# Remove the [[routes]] section as it's not needed for Pages Functions
# Pages Functions automatically handle routing based on the /functions directory 