name = "space-terminal"
compatibility_date = "2024-02-06"
pages_build_output_dir = "./dist"

[build]
command = "npm run build"
upload.format = "service-worker"

[env.production]
vars = { }  # Environment variables will be set in Cloudflare dashboard

[env.preview]
vars = { }  # Environment variables will be set in Cloudflare dashboard

[[routes]]
pattern = "/api/*"
script = "api" 